"""
生成 cc-switch 兼容的提供者配置 JSON 文件，并可通过 deep link 直接唤起 cc-switch 导入。

用法:
    python tools/export-cc-switch.py [选项]

    --env-file PATH      .env 文件路径 (默认: 仓库根目录 .env)
    --output PATH        输出 JSON 文件路径 (默认: 仓库根目录 cc-switch-provider.json)
    --name NAME          提供者名称 (默认: Sider2Claude Local)
    --port PORT          服务端口 (默认: 从 .env 读取 PORT, 否则 4141)
    --server-url URL     sider2claude 服务地址 (默认: http://127.0.0.1:PORT)
    --deeplink           同时输出 ccswitch:// deep link URL (STDERR 最后一行)
    --help               显示帮助

生成的 cc-switch-provider.json 可通过 cc-switch 桌面应用导入:
    Settings > Import/Export > Import providers

使用 --deeplink 时可直接唤起 cc-switch:
    start "<url>"
"""

import base64
import json
import sys
import urllib.parse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def parse_args():
    args = {
        "env_file": REPO_ROOT / ".env",
        "output": REPO_ROOT / "cc-switch-provider.json",
        "name": "Sider2Claude Local",
        "port": None,
        "server_url": None,
        "deeplink": False,
    }
    i = 1
    while i < len(sys.argv):
        if sys.argv[i] in ("--help", "-h"):
            print(__doc__.strip())
            sys.exit(0)
        elif sys.argv[i] == "--deeplink":
            args["deeplink"] = True
            i += 1
        elif sys.argv[i] in ("--env-file",) and i + 1 < len(sys.argv):
            args["env_file"] = Path(sys.argv[i + 1])
            i += 2
        elif sys.argv[i] in ("--output",) and i + 1 < len(sys.argv):
            args["output"] = Path(sys.argv[i + 1])
            i += 2
        elif sys.argv[i] in ("--name",) and i + 1 < len(sys.argv):
            args["name"] = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] in ("--port",) and i + 1 < len(sys.argv):
            args["port"] = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] in ("--server-url",) and i + 1 < len(sys.argv):
            args["server_url"] = sys.argv[i + 1]
            i += 2
        else:
            print(f"Unknown option: {sys.argv[i]}", file=sys.stderr)
            sys.exit(1)
    return args


def read_env(filepath: Path) -> dict:
    """读取 .env 文件，返回 key-value 字典 (去注释去空白)。"""
    values = {}
    if not filepath.exists():
        return values
    for raw in filepath.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        idx = line.index("=") if "=" in line else -1
        if idx <= 0:
            continue
        key = line[:idx].strip()
        val = line[idx + 1:].strip().strip('"').strip("'")
        values[key] = val
    return values


def build_deeplink(settings_obj: dict, provider_name: str, app: str = "claude") -> str:
    """用 ccswitch:// deep link 协议编码设置配置。

    cc-switch 解码 config base64 后直接当作 settings.json 内容，
    不要求外层 Provider 包装。Claude 需要顶层有 "env" 对象。
    """
    config_json = json.dumps(settings_obj, ensure_ascii=False, separators=(",", ":"))
    config_b64 = base64.standard_b64encode(config_json.encode("utf-8")).decode("ascii")
    params = urllib.parse.urlencode(
        {
            "resource": "provider",
            "app": app,
            "name": provider_name,
            "config": config_b64,
            "config_format": "json",
        },
    )
    return f"ccswitch://v1/import?{params}"


def export(args):
    env = read_env(args["env_file"])
    port = args["port"] or env.get("PORT", "4141")
    server_url = args["server_url"] or f"http://127.0.0.1:{port}"

    settings_obj = {
        "env": {
            "ANTHROPIC_BASE_URL": server_url,
            "ANTHROPIC_AUTH_TOKEN": "YOUR_AUTH_TOKEN",
            "ANTHROPIC_MODEL": "claude-sonnet-4-6",
            "ANTHROPIC_SMALL_FAST_MODEL": "claude-haiku-4-5",
            "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
            "CLAUDE_CODE_USE_POWERSHELL_TOOL": "1",
            "ENABLE_TOOL_SEARCH": "true",
            "API_TIMEOUT_MS": "600000",
            "BASH_DEFAULT_TIMEOUT_MS": "600000",
            "BASH_MAX_TIMEOUT_MS": "600000",
            "DISABLE_TELEMETRY": "1",
            "DISABLE_ERROR_REPORTING": "1",
        },
        "permissions": {
            "allow": [
                "Bash", "LS", "Read", "Agent", "Write", "Edit", "MultiEdit",
                "Glob", "Grep", "WebFetch", "WebSearch", "TodoWrite",
            ]
        },
    }

    provider = {
        "name": args["name"],
        "category": "third-party",
        "websiteUrl": "https://github.com/HOME-M10/sider2claude",
        "notes": (
            f"Sider2Claude local proxy on port {port}. "
            "Auto-generated by tools/export-cc-switch.py."
        ),
        # JSON 文件保持 settingsConfig 为字符串
        "settingsConfig": json.dumps(settings_obj, indent=2, ensure_ascii=False),
    }

    # Write JSON file
    output_path = args["output"]
    output_path.write_text(
        json.dumps([provider], indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[OK] cc-switch config exported: {output_path}")
    print(f"      Provider: {provider['name']}")
    print(f"      Endpoint: {server_url}")

    # Deep link: write to a sidecar file so batch can open it via PowerShell
    if args["deeplink"]:
        url = build_deeplink(settings_obj, provider["name"])
        print("")
        print(f"      Deeplink: {url[:80]}...")
        # Sidecar file path
        deeplink_path = output_path.with_suffix(".deeplink.url")
        deeplink_path.write_text(url, encoding="ascii")
        print(f"      Deeplink file: {deeplink_path}")


if __name__ == "__main__":
    export(parse_args())
